### ISSUE TITLE
Shortcuts for Mac are not the same as in the README and conflict with basic system shortcuts

### ISSUE THREAD

**Issue by certainlyakey** [VPashkov/SublimeResizeGroupWithKeyboard#3]
The shortcuts that are indicated in the README file for Mac (cmd+alt+...) are not that the plugin actually uses (cmd+shift+...), which can be seen by going [here](https://github.com/VPashkov/SublimeResizeGroupWithKeyboard/blob/master/Default%20(OSX).sublime-keymap). The latter actually conflict with basic system shortcuts [for selecting text](https://support.apple.com/en-us/HT201236). 
So the default shortcuts in the `.sublime-keymap` file should definitely be changed.

**Comment by vpashkov** [comment]
Hi!
Thank you.
I made a [fix](/VPashkov/SublimeResizeGroupWithKeyboard/commit/68842bffc3bfc0cee5a453cca4405be3f82835dc) but I need a couple of days to get to Mac to check it.

**Comment by vpashkov** [comment]
Chacked the fix on Mac. Closing this issue.
