### ISSUE TITLE
Min/Max group size

### ISSUE THREAD

**Issue by hxss** [VPashkov/SublimeResizeGroupWithKeyboard#4]
Can you add limits for resizing? Like with default mouse-resize behavior. With current plugin version I can expand pane outside the window.

**Comment by vpashkov** [comment]
Hi!
Yes, sure. I'll try to make it in near future.

**Comment by vpashkov** [comment]
Last commit (https://github.com/VPashkov/SublimeResizeGroupWithKeyboard/commit/d80c91bb160fc36a31ddb462475ce93fd813207d) should fix it.
@hxss  you can update this plugin and check out if max/min group size works.

**Comment by hxss** [comment]
Yes, it works perfect. Thank you.
